name: Format

on:
  push:
  pull_request:

jobs:
  format:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Prepare
        run: |
          npm install
          npm test
      - name: Format
        run: |
          node ./scripts/format-themes.js
          npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 'ci: format'
          branch: ${{ github.head_ref }}
